---
- hosts: all
  #ansadmin doesn't need root access to create an image
  become: true

  tasks:
 
  - name:  stop current running container
    command: docker stop simple-devops-container
    ignore_errors: yes
  
  - name: remove stopped container
    command: docker rm simple-devops-container
    ignore_errors: yes
  
  - name: remove docker image
    command: docker rmi nergalgreed/simple-devops-image:latest
    ignore_errors: yes 

    #  - name: build docker image using WAR file
    # command: docker build -t simple-devops-image .
    #args: 
    #  chdir: /opt/docker    

  - name: pull docker image from dockerhub
    command: docker pull nergalgreed/simple-devops-image:latest

  - name: create container using simple-devops-image
    command: docker run -d --name simple-devops-container -p 8080:8080 nergalgreed/simple-devops-image:latest
